### ISSUE TITLE
Freeze in Lobby

### ISSUE THREAD

**Issue by titiger** [MegaGlest/megaglest-source#104]
I got freezes in the lobby again 2 times MG was completly frozen, see stacks below.

( Maybe related: My son had problem that he lost connection to the irc in the lobby. suddenly he was no longer able to receive messages. ( this only happened once ) )

FREEZE 1
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
__lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f4e829af672 in _L_lock_953 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f4e829af4da in __GI___pthread_mutex_lock (mutex=0x3ae1270) at ../nptl/pthread_mutex_lock.c:114
#3  0x00007f4e82c847ee in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#4  0x0000000000b41b18 in p (this=0x3ae08a8, this=0x3ae08a8) at /home/tscharn/gitglest/source/shared_lib/include/platform/sdl/thread.h:143
#5  Lock (this=0x7fff17782a70) at /home/tscharn/gitglest/source/shared_lib/include/platform/sdl/thread.h:199
#6  setMutex (ownerId=..., mutex=0x3ae08a8, this=0x7fff17782a70) at /home/tscharn/gitglest/source/shared_lib/include/platform/sdl/thread.h:181
#7  Shared::PlatformCommon::IRCThread::isConnected (this=0x3ae07f0, mutexLockRequired=mutexLockRequired@entry=true) at /home/tscharn/gitglest/source/shared_lib/sources/platform/posix/ircclient.cpp:671
#8  0x00000000008035c2 in Glest::Game::MenuStateMasterserver::render (this=0x11d6bfe0) at /home/tscharn/gitglest/source/glest_game/menu/menu_state_masterserver.cpp:741
#9  0x000000000082a97b in Glest::Game::MainMenu::render (this=0x17eb8610) at /home/tscharn/gitglest/source/glest_game/menu/main_menu.cpp:192
#10 0x00000000006f4370 in Glest::Game::Program::loopWorker (this=this@entry=0x1e6d990) at /home/tscharn/gitglest/source/glest_game/main/program.cpp:449
#11 0x00000000006f6db5 in Glest::Game::Program::loop (this=this@entry=0x1e6d990) at /home/tscharn/gitglest/source/glest_game/main/program.cpp:391
#12 0x00000000006e1e4e in Glest::Game::glestMain (argc=argc@entry=1, argv=argv@entry=0x7fff17788e48) at /home/tscharn/gitglest/source/glest_game/main/main.cpp:5612
#13 0x00000000006e6456 in Glest::Game::glestMainSEHWrapper (argc=1, argv=0x7fff17788e48) at /home/tscharn/gitglest/source/glest_game/main/main.cpp:5858
#14 0x00007f4e7f721ec5 in __libc_start_main (main=0x4e82c0 <main(int, char**)>, argc=1, argv=0x7fff17788e48, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff17788e38) at
 libc-start.c:287
#15 0x00000000004ef16a in _start ()
```

FREEZE 2:
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
__lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f124e5e5672 in _L_lock_953 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f124e5e54da in __GI___pthread_mutex_lock (mutex=0x3b3b570) at ../nptl/pthread_mutex_lock.c:114
#3  0x00007f124e8ba7ee in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#4  0x0000000000b41b18 in p (this=0x3a8fe58, this=0x3a8fe58) at /home/tscharn/gitglest/source/shared_lib/include/platform/sdl/thread.h:143
#5  Lock (this=0x7ffd4f78dab0) at /home/tscharn/gitglest/source/shared_lib/include/platform/sdl/thread.h:199
#6  setMutex (ownerId=..., mutex=0x3a8fe58, this=0x7ffd4f78dab0) at /home/tscharn/gitglest/source/shared_lib/include/platform/sdl/thread.h:181
#7  Shared::PlatformCommon::IRCThread::isConnected (this=0x3a8fda0, mutexLockRequired=mutexLockRequired@entry=true) at /home/tscharn/gitglest/source/shared_lib/sources/platform/posix/ircclient.cpp:671
#8  0x00000000008035c2 in Glest::Game::MenuStateMasterserver::render (this=0x3af8ae0) at /home/tscharn/gitglest/source/glest_game/menu/menu_state_masterserver.cpp:741
#9  0x000000000082a97b in Glest::Game::MainMenu::render (this=0x2539ca0) at /home/tscharn/gitglest/source/glest_game/menu/main_menu.cpp:192
#10 0x00000000006f4370 in Glest::Game::Program::loopWorker (this=this@entry=0x1ed0960) at /home/tscharn/gitglest/source/glest_game/main/program.cpp:449
#11 0x00000000006f6db5 in Glest::Game::Program::loop (this=this@entry=0x1ed0960) at /home/tscharn/gitglest/source/glest_game/main/program.cpp:391
#12 0x00000000006e1e4e in Glest::Game::glestMain (argc=argc@entry=1, argv=argv@entry=0x7ffd4f793e88) at /home/tscharn/gitglest/source/glest_game/main/main.cpp:5612
#13 0x00000000006e6456 in Glest::Game::glestMainSEHWrapper (argc=1, argv=0x7ffd4f793e88) at /home/tscharn/gitglest/source/glest_game/main/main.cpp:5858
#14 0x00007f124b357ec5 in __libc_start_main (main=0x4e82c0 <main(int, char**)>, argc=1, argv=0x7ffd4f793e88, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd4f793e78) at
 libc-start.c:287
#15 0x00000000004ef16a in _start ()
```

**Comment by titiger** [comment]
should be fixed, if not I reopen it or make new issue.
