### ISSUE TITLE
FreeBSD, froze, crash and core dump during closing map editor

### ISSUE THREAD

**Issue by filux** [MegaGlest/megaglest-source#74]
How to reproduce: Try to close map editor by "X" button, then you will get question about saving map, after any answer is froze, crash and core dump.

```
megaglest v3.12-dev
Compiled using: Clang: 3.4.1 [64bit] on: Oct  8 2015 12:56:29 platform: FreeBSD-X64 endianness: little
GIT: [Rev: 5170.02fe61e] - using STREFLOP [SSE] - [no-denormals]
```

```
[New process 100145]
[New process 100336]
[New process 100335]
[New process 100332]
[New process 100331]
[New process 100330]
[New process 100329]
[New Thread 81c43ec00 (LWP 100336)]
[New Thread 817210400 (LWP 100335)]
[New Thread 817203c00 (LWP 100332)]
[New Thread 817203800 (LWP 100331)]
[New Thread 817011c00 (LWP 100330)]
[New Thread 817011800 (LWP 100329)]
[New Thread 817006400 (LWP 100145)]
Core was generated by `megaglest_editor'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000080101a55a in glXDestroyContext () from /usr/local/lib/libGL.so.1
#0  0x000000080101a55a in glXDestroyContext () from /usr/local/lib/libGL.so.1
#1  0x0000000802072dce in wxGLContext::~wxGLContext() () from /usr/local/lib/libwx_gtk2u_gl-3.0.so.0
#2  0x0000000802072d4e in wxGLContext::~wxGLContext() () from /usr/local/lib/libwx_gtk2u_gl-3.0.so.0
#3  0x000000000043ec46 in ~GlCanvas (this=0x817111f00) at /usr/home/filux/megaglest-git/source/glest_map_editor/main.cpp:1485
#4  MapEditor::GlCanvas::~GlCanvas (this=0x817111f00) at /usr/home/filux/megaglest-git/source/glest_map_editor/main.cpp:1484
#5  0x000000080181cd78 in wxWindowBase::Destroy() () from /usr/local/lib/libwx_gtk2u_core-3.0.so.0
#6  0x0000000000434b56 in MapEditor::MainWindow::onClose (this=0x81712a400, event=...) at /usr/home/filux/megaglest-git/source/glest_map_editor/main.cpp:483
#7  0x0000000801db4024 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () from /usr/local/lib/libwx_baseu-3.0.so.0
#8  0x0000000801db531d in wxEvtHandler::ProcessEventLocally(wxEvent&) () from /usr/local/lib/libwx_baseu-3.0.so.0
#9  0x0000000801db520e in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/local/lib/libwx_baseu-3.0.so.0
#10 0x0000000801db562f in wxEvtHandler::SafelyProcessEvent(wxEvent&) () from /usr/local/lib/libwx_baseu-3.0.so.0
#11 0x000000080181cdeb in wxWindowBase::Close(bool) () from /usr/local/lib/libwx_gtk2u_core-3.0.so.0
#12 0x00000008016a62c4 in ?? () from /usr/local/lib/libwx_gtk2u_core-3.0.so.0
#13 0x0000000806f59f5f in _gtk_marshal_BOOLEAN__BOXED () from /usr/local/lib/libgtk-x11-2.0.so.0
#14 0x0000000808819912 in g_closure_invoke () from /usr/local/lib/libgobject-2.0.so.0
#15 0x000000080882e593 in ?? () from /usr/local/lib/libgobject-2.0.so.0
#16 0x000000080882f39e in g_signal_emit_valist () from /usr/local/lib/libgobject-2.0.so.0
#17 0x000000080882fa24 in g_signal_emit () from /usr/local/lib/libgobject-2.0.so.0
#18 0x00000008070835bc in ?? () from /usr/local/lib/libgtk-x11-2.0.so.0
#19 0x0000000806f57bee in gtk_main_do_event () from /usr/local/lib/libgtk-x11-2.0.so.0
#20 0x000000080749bfb1 in ?? () from /usr/local/lib/libgdk-x11-2.0.so.0
#21 0x0000000808ca0fb8 in g_main_context_dispatch () from /usr/local/lib/libglib-2.0.so.0
#22 0x0000000808ca134e in ?? () from /usr/local/lib/libglib-2.0.so.0
#23 0x0000000808ca165f in g_main_loop_run () from /usr/local/lib/libglib-2.0.so.0
#24 0x0000000806f574cf in gtk_main () from /usr/local/lib/libgtk-x11-2.0.so.0
#25 0x00000008016985b5 in wxGUIEventLoop::DoRun() () from /usr/local/lib/libwx_gtk2u_core-3.0.so.0
#26 0x0000000801cd5dd9 in wxEventLoopBase::Run() () from /usr/local/lib/libwx_baseu-3.0.so.0
#27 0x0000000801c97fb6 in wxAppConsoleBase::MainLoop() () from /usr/local/lib/libwx_baseu-3.0.so.0
#28 0x000000000043f981 in MapEditor::App::MainLoop (this=0x8170c8000) at /usr/home/filux/megaglest-git/source/glest_map_editor/main.cpp:1696
#29 0x0000000801d11237 in wxEntry(int&, wchar_t**) () from /usr/local/lib/libwx_baseu-3.0.so.0
#30 0x000000000044018a in main (argc=1, argv=0x6372) at /usr/home/filux/megaglest-git/source/glest_map_editor/main.cpp:1753
```

**Comment by filux** [comment]
same situation on 9fc7b9f

**Comment by Jammyjamjamman** [comment]
Closing this ticket, because it's very outdated. Please open another ticket if you have similar problems.
