### ISSUE TITLE
freeze in lobby

### ISSUE THREAD

**Issue by titiger** [MegaGlest/megaglest-source#89]
in internet menu I got a freeze and I was able to catch this stacktrace:
http://pastebin.com/YTBiDATz

``` c++
[New LWP 14467]
[New LWP 14238]
[New LWP 14226]
[New LWP 14222]
[New LWP 14221]
[New LWP 14220]
[New LWP 14218]
[New LWP 14216]
[New LWP 14214]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
__lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
135	../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S: Datei oder Verzeichnis nicht gefunden.
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007feb52e9c672 in _L_lock_953 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007feb52e9c4da in __GI___pthread_mutex_lock (mutex=0x4ec25d0) at ../nptl/pthread_mutex_lock.c:114
#3  0x00007feb531717ee in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#4  0x0000000000b227e7 in Shared::Platform::Mutex::p (this=0x4ecf7e8) at /home/tscharn/gitglest/source/shared_lib/sources/platform/sdl/thread.cpp:532
#5  0x0000000000b3b8c5 in Lock (this=0x7fffb926b630) at /home/tscharn/gitglest/source/shared_lib/include/platform/sdl/thread.h:193
#6  setMutex (ownerId=..., mutex=0x4ecf7e8, this=0x7fffb926b630) at /home/tscharn/gitglest/source/shared_lib/include/platform/sdl/thread.h:175
#7  Shared::PlatformCommon::IRCThread::isConnected (this=0x4ecf730, mutexLockRequired=mutexLockRequired@entry=true) at /home/tscharn/gitglest/source/shared_lib/sources/platform/posix/ircclient.cpp:671
#8  0x00000000007ff19c in Glest::Game::MenuStateMasterserver::render (this=0x64215c0) at /home/tscharn/gitglest/source/glest_game/menu/menu_state_masterserver.cpp:741
#9  0x00000000008267db in Glest::Game::MainMenu::render (this=0x354bf100) at /home/tscharn/gitglest/source/glest_game/menu/main_menu.cpp:192
#10 0x00000000006f3340 in Glest::Game::Program::loopWorker (this=this@entry=0x325adf0) at /home/tscharn/gitglest/source/glest_game/main/program.cpp:449
#11 0x00000000006f5d85 in Glest::Game::Program::loop (this=this@entry=0x325adf0) at /home/tscharn/gitglest/source/glest_game/main/program.cpp:391
#12 0x00000000006e12fc in Glest::Game::glestMain (argc=argc@entry=1, argv=argv@entry=0x7fffb9271a08) at /home/tscharn/gitglest/source/glest_game/main/main.cpp:5589
#13 0x00000000006e5276 in Glest::Game::glestMainSEHWrapper (argc=1, argv=0x7fffb9271a08) at /home/tscharn/gitglest/source/glest_game/main/main.cpp:5835
#14 0x00007feb4fc0dec5 in __libc_start_main (main=0x4e77c0 <main(int, char**)>, argc=1, argv=0x7fffb9271a08, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffb92719f8) at
 libc-start.c:287
#15 0x00000000004ee63a in _start ()
```

**Comment by tomreyn** [comment]
Note this occurred around the time the masterserver (and the server hosting it) became unresponsive.

**Comment by titiger** [comment]
Thats true, but as far as I know the masterserver was ok, just our headless servers had trouble. 
I think its not related. And freeze in this lobby happens form time to time so I was happy to catch this.

**Comment by softcoder** [comment]
Hopefully fixed by latest push

**Comment by titiger** [comment]
this problem did not show up anymore, I close this ticket for now,
